// <auto-generated />
namespace BookingBlock.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bt));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081747143_bt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
