// <auto-generated />
namespace BookingBlock.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bookinglogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookinglogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201604231751367_bookinglogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
